---
name: Telethon to Home Assistant
version: 1.0.2
slug: telethon2sensor
description: Telegram chatbot messages listener for Home Assistant
url: https://github.com/semitop7/telethon2sensor
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: ghcr.io/semitop7/{arch}-addon-telethon2sensor
homeassistant_api: true
options:
  api_id: ""
  api_hash: ""
  api_session: ""
  chat_bot_username: "@loeserviceBot"
  confirmation_message: |
    Шановний m'lord!
    Автоматизацію на увімкнення Bluetti AC200MAX АС інвертору створено на {time}.
    Home Assistant все виконає автоматично замість вас, розслабтесь та насолоджуйтесь життям!
  debug: false
schema:
  api_id: str
  api_hash: str
  api_session: match(^[0-9A-Za-z\-_=]*$)
  chat_bot_username: str
  confirmation_message: match(^.*\{time\}.*$)
  debug: bool
